version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    networks:
      - main
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    networks:
      - main
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  mongo:
    image: mongo
    container_name: mongo
    networks:
      - main
    ports:
        - '27017:27017'
    restart: always
    environment:
        - MONGO_INITDB_ROOT_USERNAME=mongoadmin
        - MONGO_INITDB_ROOT_PASSWORD=mysecretpass
    logging:
        options:
            max-size: 1g

  api:
    container_name: api
    networks:
      - main
    build:
      context: api
      dockerfile: Dockerfile
    ports:
        - '5001:5001'
    restart: always
    environment:
        - DB_USER=mongoadmin
        - DB_PASSWORD=mysecretpass
        - DB_ADDRESS=mongo
        - KAFKA_ADDRESS=kafka
    depends_on:
      - mongo
      - kafka

  web:
    container_name: web
    networks:
      - main
    build:
      context: web
      dockerfile: Dockerfile
    ports:
        - '5002:5002'
    restart: always
    environment:
        - KAFKA_ADDRESS=kafka
        - API_ADDRESS=api
    depends_on:
      - kafka

networks:
  main:
    driver: bridge